Repository gnosis/ethcontract-rs, pull requests merged in 2021-06, with the labels that each got.

#529 Release v0.12.2
  ethcontract-common/Cargo.toml
  ethcontract-derive/Cargo.toml
  ethcontract-generate/Cargo.toml
  ethcontract/Cargo.toml
Labels: merge when green

#537 Add convenience methods for tx confirmation settings struct
  ethcontract/src/transaction/confirm.rs
Labels: enhancement

#535 Don't use filters to wait for tx confirmation, use polling instead
  ethcontract/src/transaction.rs
  ethcontract/src/transaction/confirm.rs
Labels: bug

#538 Add exponential backoff for transaction confirmation polling
  ethcontract/src/transaction/confirm.rs
Labels: enhancement

#539 Add pull request template
  .github/pull_request_template.md
Labels: trivial

#543 Rename truffle::Artifact to contract::Contract
  ethcontract-common/src/contract.rs
  ethcontract-common/src/lib.rs
  ethcontract-generate/src/contract.rs
  ethcontract-generate/src/contract/common.rs
  ethcontract-generate/src/contract/deployment.rs
  ethcontract-generate/src/contract/events.rs
  ethcontract-generate/src/contract/methods.rs
  ethcontract-generate/src/lib.rs
  ethcontract-generate/src/source.rs
  ethcontract/src/contract.rs
  ethcontract/src/contract/deploy.rs
  ethcontract/src/lib.rs
Labels: cleanup

#546 Remove compatibility with old ethabi parsing
  ethcontract-common/src/contract.rs
  ethcontract-generate/src/contract/methods.rs
  ethcontract/src/contract.rs
Labels: cleanup, enhancement

#544 Add Artifact trait
  ethcontract-common/src/artifact.rs
  ethcontract-common/src/artifact/truffle.rs
  ethcontract-common/src/contract.rs
  ethcontract-common/src/lib.rs
  ethcontract-generate/src/contract.rs
Labels: enhancement

#548 Implement artifact loader for hardhat export
  ethcontract-common/src/artifact.rs
  ethcontract-common/src/artifact/hardhat.rs
  ethcontract-common/src/artifact/truffle.rs
  ethcontract-common/src/errors.rs
Labels: enhancement

#553 Use existing ABI reimport
  ethcontract-common/src/contract.rs
Labels: cleanup, trivial
